mcstatus/server.py

This fixes some servers with long DNS queries or slow resolution not getting UDP queries correctly.
This only matters for the UDP case as it'll resolve the DNS each time a packet is sent, spending extra time or receiving an invalid/different record each time. TCP methods (ping) don't have this issue since they maintain the connection opened (so only one DNS resolution is made).

Resolve DNS before sending packets

---

mcstatus/protocol/connection.py
mcstatus/tests/protocol/test_connection.py

This commit fixes #24 by simply checking whether the socket received any data at all. If it did not, an IOError is raised.
It might be that we should try to recieve multiple times before the IOError is raised, but this is not implemented in this commit as to avoid bloat.

Raise IOError when TCPConnection.read(length) recieves no data.

---

setup.py

It turns out distutils cannot easily check for installed packages and makes
no effort to install missing packages. Setuptools on the other hand will
gladly do this for use.
This way situations like #33 cannot arise.

Use setuptools to enable dependency checking

---

mcstatus/protocol/connection.py

TCP / UDP Sockets used in the Connection class dont get closed (so urllib3 was complaining).
Putting the .close() into __del__(self) will close it implicitly when Connection goes out of scope.
I'm not 100% sure if sockets got closed by GC before, but this cleans up the logfile when using mcstatus with bottlepy.

Implicitly close sockets in destructor methods

---

mcstatus/scripts/mcstatus.py

Following #51 the code was rebased then changed to use `json.dumps`. Tested successfully on some servers from [minecraftservers.org](https://minecraftservers.org) (when ping worked, otherwise it showed `{"online": false}`)

JSON format with "mcstatus [address] json"

---

mcstatus/server.py

Changed the "retries" variable names in the actionable methods found in `server.py` to 'tries' which better represent what they are being treated as. (Ex previous: when setting retries=0, the method would not try once. However it should try at least once before attempting a **retry**)

Variable name change

---

.travis.yml
setup.py

Closes #105. I'll continue to rely on Travis for testing the multiple Python versions until I find a nice way of using tox + poetry (in other words, I need to find some spare time in my life).
Bumping major version.

Drop support for python 3.5

---

mcstatus/pinger.py

Per PEP 8, if you wanted to apply this.
The big case in which I can think of that this'd be an issue is if mcstatus were to be integrated as a dependency of some larger project that had its own subclassed types, it might avoid some breakage in that case.

Change "type(x) is y" to "isinstance(x, y)"

---

requirements.txt
setup.py

Hi,
I noticed the requirements in `requirements.txt` and the install_requires in `setup.py` don't match. This was causing some requirement issues when installing the lastest versions (5.0.0/5.1.0) from PyPI since `asyncio-dgram` is missing from the `setup.py` install_requires.
To fix this, I've changed `setup.py` to read from the requirements files.

Read requirements from file in setup.py

---

mcstatus/scripts/mcstatus.py

Looks like https://github.com/Dinnerbone/mcstatus/pull/89 didn't update the CLI, which still had `retries` passed to the `status` and `query` commands. As a result, `mcstatus <server> json` was just returning `online` and `ping`, without any of the extra data.

Rename retries argument in CLI

---

mcstatus/protocol/connection.py

Make varint reading and writing functions use C int 32's with ctypes module.
Important: Writing converts value to unsigned_int32, so that signed bit get forced to turn into a part of the number for writing, sort of breaking the number so python handles it like Java and C would. Reading converts final value back to signed_int32 so that the number is correct when python tries to use it.

Fix varint reading and writing. Closes #141

---

mcstatus/querier.py
mcstatus/tests/test_async_querier.py
mcstatus/tests/test_querier.py
mcstatus/tests/test_server.py
mcstatus/tests/test_session_id.py

This library seems to not conform to minecraft query protocol.
This PR fixes inconsistencies and cleans up query packet handling. Tests are provided.
It now queries PocketMine-MP servers, as well as regular java edition servers.
Closes #145, properly.
Details on fixes (from https://wiki.vg/Query which seems to be the closest to the truth on minecraft protocol):
1. There was an extra zero int written to the handshake packet, now it conforms to this:
2. Cleaned up request packet generation as well, it all is now handled in one place, rather than doing most of the work in a single method and then adding a padding. It conforms to this:
Functionally not a lot changes.
3. Querier now generates proper session ids instead of always using 0, which helps readability and is more correct.
GameSpot) …

Query protocol fixes

---

mcstatus/protocol/connection.py
mcstatus/tests/test_server.py
mcstatus/tests/test_timeout.py

TCPAsyncSocketConnection uses `asyncio.wait_for` wrapper only when connecting.
Now it uses it for reading as well, as per usual, test included.

TCPAsyncSocketConnection bugfix

---

mcstatus/pinger.py

This PR implements the following (Resolves #147):
- Instead of ignoring formatted text in server MOTDs/descriptions, the code will now stringify the MOTD using Minecraft formatting codes into something like this: `'         §6The §k§4||§l§9CubeCraft§k§4||§f §6Network §a[NA 1.12.2+]\n   §l§c◆§f §l§bNEW 1.12 MAPS§f §l§7+§f §l§eEPIC PARKOUR UPDATE!§f §l§c◆§f'`
- Use `raw.get("favicon")` instead of checking to see if the favicon field exists in the raw data.
I tested this PR on `hypixel.net`, `cubecraft.net`, and `xenon.iapetus11.me` and it worked perfectly.

Update the creation of the description field + minor change to favicon field

---

mcstatus/bedrock_status.py

`BedrockServerStatus.read_status_async()` does not handle properly the case of a server hanging, this PR simply adds `asyncio.wait_for(.., timeout=...)` wrapper in a few places.

timeout bedrock status comms

---

README.md
mcstatus/pinger.py
mcstatus/scripts/address_tools.py
mcstatus/scripts/mcstatus.py

Since python 3.6, support for "f-strings" was added, this allows us to format strings in a very simple way:
```py
variable = "some value"
foo = f"This string contains {variable}"
```
This is much more readable than using `str.format` or the `%` formatting notation.
I assume the reason these older ways to format strings was to keep the library compatible with older python versions, however at the moment, this library supports >=3.6 which allows us to utilize these f-strings instead of the less readable methods.

Use f-strings instead of % formatting or str.format

---

poetry.lock
pyproject.toml
tox.ini

Closes #183
As described in the issue, python 3.6 has reached end of life and support for it should be dropped.
Note: Dropping 3.6 also allows for some code-base improvements such as the use of dataclasses and other features which was also mentioned in the issue. This PR does NOT implement any of these changes since I feel like that should be left for other specific pull requests with this one only dropping the support for the version itself. However, since this isn't a particularly pressing PR to get merged, if requested, I'm fine with implementing these improvements in here along with dropping it from supported versions, perhaps to avoid forgetting about doing it.

Drop support for python 3.6

---

mcstatus/server.py

Closes #173
As mentioned in the issue, the timeout parameter has been added in the lookup functions and propagated to the appropriate functions.
I have done some small functional / visual testing, which are not included. I only tested MinecraftServer since I don't have a BedrockServer and I tested ping, status and query and also the async variants.
During my small functional testing, I observed that if the URL of the server is a domain name, socket.create_connection can take longer than the specified timeout. This is better described here :
https://stackoverflow.com/questions/12232225/python-3-2-3-socket-takes-longer-to-timeout-than-it-should

Add timeout parameter propagation from lookup func

---

mcstatus/server.py
mcstatus/tests/test_retry_decorator.py
mcstatus/utils.py

Closes #139
As discussed in the issue, this introduces a retry decorator which will automate the logic of retrying the code for several specified amount of tries until the function was successful or if the function failed in each of the tries, raise the last exception that occurred.

Merge retry logic into a single decorator

---

mcstatus/server.py

Closes #189 
As shown in the issue, not having any checks for valid values of the server's address can lead to the instance being made without any hint of an error, even though it has unexpected internal values which will be causing issues later. Whenever this happens, since the error will only appear in later usage of this instance, It will not be easy to recognize what's going on. To prevent this, this PR adds a function which simply raises an exception during initialization if the values aren't valid, therefore preventing even the creation of an instance with invalid values.
Note: I've also used regex to ensure that the host address is valid, however I'm not entirely sure if this pattern catches all possible host values correctly, so please make sure to test this before approving the …

Ensure the address is valid on server init

---

README.md

Originally, when clicking on the PyPI badge in README, it redirected you to an image of that badge. This changes this behavior to instead redirect to the PyPI mcstatus repository, making it a lot more convenient.

Link to PyPI repo from the badge

---

mcstatus/server.py

After an [approval from discord](https://discord.com/channels/936788458939224094/936788458939224097/938273648316416001), this PR uses the recently added `Self` type annotation from [PEP 673](https://www.python.org/dev/peps/pep-0673/), scheduled to be added into python in 3.11 to annotate alternative constructors easily without having to make individual type variables for each class that needs them just to support subclassing.
Even though this type annotation isn't yet in python's standard library, the `typing_extensions` package does already contain it and pyright type checker does already full support it.

Annotate alternative constructors with Self

---

mcstatus/querier.py
mcstatus/tests/test_querier.py

If `motd` set to unicode in `server.properties` , using other parameters of `read_ascii()` may be in the wrong order. (0x00 not unicode end)
Since the minecraft protocol does not support unicode, the hostname is still not resolved correctly.
However, this will avoid other parameter parsing errors.

fix motd unicode parse error.

---

mcstatus/bedrock_status.py
mcstatus/pinger.py
mcstatus/protocol/connection.py
mcstatus/querier.py
mcstatus/scripts/address_tools.py
mcstatus/scripts/mcstatus.py
mcstatus/server.py
mcstatus/utils.py
poetry.lock
pyproject.toml

As [discussed in the Discord server](https://canary.discord.com/channels/936788458939224094/936788458939224097/940395422101430302), this PR:
* removes unnecessary typing_extensions dependency (and hides the import under a `TYPE_CHECKING` condition)
* postpones annotation evaluation by placing `from __future__ import annotations` in all files (excluding tests)
* ~~corrects the usage of typing.Self by type-hinting `cls`~~
Edit: after re-reading [PEP-673](https://www.python.org/dev/peps/pep-0673), I realized that I was mistaken, and that the previous usage of `typing.Self` was correct. I have reverted this change.

Improve library typehints

---

mcstatus/tests/protocol/test_connection.py
mcstatus/tests/test_server.py
mcstatus/tests/test_session_id.py
mcstatus/tests/test_timeout.py
poetry.lock
pyproject.toml

We were using the `mock` module because it provided a backport of `unittest.mock` over to older python versions, however these versions are no longer supported by this project and so using it isn't necessary anymore.

Remove 'mock' in favor of stdlib 'unittest mock'
